### ISSUE TITLE
tolerating unexpected fields in config file

### ISSUE THREAD

**Issue by aimichal** [allenai/beaker-py#125]
Looks like beaker-py uses yaml.load() which does not allow unexpected fields in the config file.

Minimal repro of usage:

```py
import yaml

from dataclasses import asdict, dataclass, fields

@dataclass
class Config:
    foo: str

    @classmethod
    def loadit(cls):
        with open("somefile.yaml") as config_file:
            return cls(**yaml.load(config_file, Loader=yaml.SafeLoader))

Config.loadit()
```

with file somefile.yaml:

```
a: 42
foo: "Asdf"
```

yields:

```
TypeError: __init__() got an unexpected keyword argument 'a'
```

As an aside:

The PyYAML documentation at https://pyyaml.org/wiki/PyYAMLDocumentation suggests not to use `yaml.load()` from untrusted sources:

> Warning: It is not safe to call yaml.load with any data received from an untrusted source! yaml.load is as powerful as pickle.load and so may call any Python function. Check the yaml.safe_load function though.

Is that better to use than providing `Loader=yaml.SafeLoader`?

**Comment by epwalsh** [comment]
Seems like `yaml.safe_load` is equivalent to `yaml.load(.., Loader=yaml.SafeLoader)`.
