### ISSUE TITLE
Fetching experiments from a workspace results in exception

### ISSUE THREAD

**Issue by rajcscw** [allenai/beaker-py#143]
### 🐛 Describe the bug

I am trying to get all experiments from a workspace:

```
exps = beaker_client.workspace.experiments(workspace="ai2/nlpgym2.0")
print(len(exps))
```

But this results in following error:

`  File "/Users/rramamurth/opt/miniconda3/envs/nlpgym2/lib/python3.7/site-packages/beaker/data_model/base.py", line 51, in from_json
    return cls(**json_data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ExperimentsPage
data -> 95 -> jobs -> 2 -> execution -> spec -> image -> __root__
  Exactly one of 'beaker' or 'docker' must be specified for image source (type=value_error)`

### Versions

Python 3.7.13
absl-py==1.0.0
aiohttp==3.8.1
aiosignal==1.2.0
astunparse==1.6.3
async-timeout==4.0.2
asynctest==0.13.0
attrs==21.4.0
autopep8==1.6.0
beaker-py==1.6.4
bert-score==0.3.11
BLEURT @ git+https://github.com/google-research/bleurt.git@c6f2375c7c178e1480840cf27cb9e2af851394f9
cached-property==1.5.2
cachetools==5.1.0
certifi==2022.5.18.1
charset-normalizer==2.0.12
click==8.1.3
cloudpickle==1.6.0
colorama==0.4.4
commonmark==0.9.1
cycler==0.11.0
datasets==2.0.0
dill==0.3.5.1
diskcache==5.4.0
docker==5.0.0
docker-pycreds==0.4.0
filelock==3.7.0
flake8==4.0.1
flatbuffers==1.12
fonttools==4.33.3
frozenlist==1.3.0
fsspec==2022.5.0
gast==0.4.0
gem-metrics @ git+https://github.com/GEM-benchmark/GEM-metrics.git@431a8174bd6b3637e8d6118bfad2983e39e99733
gitdb==4.0.9
GitPython==3.1.27
google-auth==2.6.6
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.46.3
gym==0.19.0
h5py==3.6.0
huggingface-hub==0.6.0
idna==3.3
importlib-metadata==4.11.4
iniconfig==1.1.1
joblib==1.1.0
jsonlines==3.0.0
keras==2.9.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.2
libclang==14.0.1
logzero==1.7.0
Markdown==3.3.7
matplotlib==3.5.2
mccabe==0.6.1
multidict==6.0.2
multiprocess==0.70.12.2
-e git+ssh://git@github.com/allenai/nlp-gym2.git@b40a06a44c342fe0cb49a6b2f6911224d56902a5#egg=nlp_gym
nltk==3.7
numpy==1.21.6
oauthlib==3.2.0
opt-einsum==3.3.0
overrides==3.1.0
packaging==21.3
pandas==1.3.5
pathtools==0.1.2
Pillow==9.1.1
pluggy==0.13.1
portalocker==2.4.0
promise==2.3
protobuf==3.20.1
psutil==5.9.1
py==1.11.0
pyarrow==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.8.0
pycountry==22.3.5
pydantic==1.9.1
pyflakes==2.4.0
Pygments==2.12.0
pyparsing==3.0.9
pytest==6.2.4
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
regex==2022.4.24
repro==0.1.4
requests==2.27.1
requests-oauthlib==1.3.1
responses==0.18.0
rich==12.4.4
rouge-score==0.0.4
rsa==4.8
sacrebleu==2.1.0
sacremoses==0.0.53
scipy==1.7.3
seaborn==0.11.2
sentencepiece==0.1.96
sentry-sdk==1.5.12
setproctitle==1.2.3
shortuuid==1.0.9
six==1.16.0
smmap==5.0.0
stable-baselines3==1.4.0
tabulate==0.8.9
tensorboard==2.9.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.9.0
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.26.0
termcolor==1.1.0
tf-slim==1.1.0
tokenizers==0.12.1
toml==0.10.2
torch==1.11.0
torchvision==0.12.0
tqdm==4.64.0
transformers==4.18.0
typing_extensions==4.2.0
urllib3==1.26.9
wandb==0.12.15
websocket-client==1.3.2
Werkzeug==2.1.2
wrapt==1.14.1
xxhash==3.0.0
yarl==1.7.2
zipp==3.8.0

**Comment by epwalsh** [comment]
This is odd. I can see from your experiment spec that you specified a Beaker image: https://beaker.org/ex/01G9JVQXV3YR4KAR0KESH56ZAF/spec

But for some reason it's not included in the data sent from the API (`GET /experiments/01G9JVQXV3YR4KAR0KESH56ZAF`):

```
{
    'kind': 'execution',
    'id': '01G9N2ASZKFQMT6C5Y3RJA71N6',
    'name': 'dcb19b45f40731ed7c1a2b03c270663e',
    'author': {'id': '01FZTZE8TPN3CE7YJMY7NCQE2C', 'name': 'rajkumarrrk', 'displayName': 'Rajkumar', 'pronouns': ''},
    'workspace': '01G0FHSCTS85BP92Z68YPGX2GQ',
    'cluster': 'us_wvnghctl47k0/01FP9NDDSZP9GM6AKJA01QS573',
    'status': {
        'created': '2022-08-04T18:36:52.593596Z',
        'failed': '2022-08-04T18:36:52.593596Z',
        'finalized': '2022-08-04T18:36:52.593596Z',
        'message': 'image rajkumarrrk/nlpgym2.0: image "rajkumarrrk/nlpgym2.0" not found'
    },
    'requests': {'gpuCount': 6},
    'execution': {
        'task': '01G9JVQXWE6YTXWN4427VQJ1NQ',
        'experiment': '01G9JVQXV3YR4KAR0KESH56ZAF',
        'workspace': '01G0FHSCTS85BP92Z68YPGX2GQ',
        'spec': {
            'name': 'dcb19b45f40731ed7c1a2b03c270663e',
            'image': {},
            'command': [
                'python',
                '-u',
                'demo_scripts/training/train_text_generation.py',
                '--project_name',
                'gpt2_sent_cont_ppo',
                '--experiment_name',
                'dcb19b45f40731ed7c1a2b03c270663e',
                '--base_path_to_store_results',
                '/output',
                '--entity_name',
                'nlp-gym',
                '--log_to_wandb',
                '--config_path',
                '/data/text_continuation_sentiment.yml'
            ],
            'envVars': [{'name': 'WANDB_API_KEY', 'secret': 'WANDB_API_KEY'}],
            'result': {'path': '/output'},
            'resources': {'gpuCount': 6},
            'context': {'cluster': 'us_wvnghctl47k0/01FP9NDDSZP9GM6AKJA01QS573', 'priority': 'normal'}
        },
        'result': {'beaker': '01G9N2ASZHGMENGC1G02KXJWJ7'}
    }
}
```

@codeviking, @aimichal, @katepanter, @mewil any idea? Looks like the exp failed b/c that image couldn't be found. Maybe that has something to do with it 🤷‍♂️

**Comment by rajcscw** [comment]
May be the experiment failed because I was in the process of uploading a new image (after deleting the previous one). Happened to me once. 

But why would it throw error while fetching experiments now..

**Comment by epwalsh** [comment]
It's a data validation error on the client side (beaker-py being the client). Beaker-py is throwing an error because the `image` field in the experiment spec is supposed to have a `docker` or `beaker` field, and in this case there is neither in the data returned from the server. So I think it's a bug on the server side.

**Comment by rajcscw** [comment]
Okay thanks for the info. As a workaround, on the client side, you can try to continue fetching the experiments (although one of the experiment's data validation fails) ? 

I am just trying to list all experiment IDs from the workspace (with a filter on the description field). I would appreciate if you could suggest me an alternative solution (using beaker CLI is also fine)

**Comment by epwalsh** [comment]
Could you just delete that experiment for now? You could also use the CLI:

```
beaker workspace experiments ai2/nlpgym2.0
```
