### ISSUE TITLE
`beaker.experiment.create` should allow for an empty (or None) name

### ISSUE THREAD

**Issue by jlcmoore** [allenai/beaker-py#256]
### 🚀 The feature, motivation and pitch

The beaker command line, such as `beaker experiment create spec.yaml`, does not require that you specify a name. If no name is provided it defaults to the experiment id. This is not the same behavior as in `beaker.experiment.create` which requires a non empty string name.

I am running many experiments using `beaker.experiment.create`, some of which fail (at least during the testing process). Thus coming up with unique, meaningful names for each experiment is challenging (recall that beaker requires experiment names to be unique, unless they have been manually deleted). I can get around this by using a hash or something of that sort but it would be more elegant to simply allow the experiment id to be the name. Thanks for considering!

**Comment by epwalsh** [comment]
Hey @jlcmoore, I've opened #257 to fix this.
