### ISSUE TITLE
JSON validation error when calling beaker.cluster.utilization

### ISSUE THREAD

**Issue by rbgirshick** [allenai/beaker-py#268]
### 🐛 Describe the bug

Repro:

```python
from beaker import Beaker

beaker = Beaker.from_env(default_workspace="ai2/rbg_dev")
beaker.cluster.utilization("ai2/prior-cirrascale")
```

Results in:

```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[9], line 1
----> 1 beaker.cluster.utilization("ai2/prior-cirrascale")

File ~/miniconda3/envs/base-dev/lib/python3.11/site-packages/beaker/services/cluster.py:221, in ClusterClient.utilization(self, cluster)
    210 running_preemptible_jobs = 0
    211 node_to_util: Dict[str, Dict[str, Union[int, float]]] = {
    212     node.id: {
    213         "running_jobs": 0,
   (...)
    218     for node in nodes
    219 }
--> 221 for job in self.beaker.job.list(cluster=cluster, finalized=False):
    222     if job.status.current in (CurrentJobStatus.running, CurrentJobStatus.idle):
    223         if job.node not in node_to_util:

File ~/miniconda3/envs/base-dev/lib/python3.11/site-packages/beaker/services/job.py:100, in JobClient.list(self, cluster, experiment, finalized, kind, node)
     98 # Gather jobs, page by page.
     99 while True:
--> 100     page = Jobs.from_json(self.request("jobs", method="GET", query=request_opts).json())
    101     if page.data:
    102         jobs.extend(page.data)

File ~/miniconda3/envs/base-dev/lib/python3.11/site-packages/beaker/data_model/base.py:68, in BaseModel.from_json(cls, json_data)
     65 @classmethod
     66 def from_json(cls: Type[T], json_data: Dict[str, Any]) -> T:
     67     try:
---> 68         return cls(**json_data)
     69     except ValidationError:
     70         logger.error("Error validating raw JSON data for %s: %s", cls.__name__, json_data)

File ~/miniconda3/envs/base-dev/lib/python3.11/site-packages/pydantic/main.py:171, in BaseModel.__init__(self, **data)
    169 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    170 __tracebackhide__ = True
--> 171 self.__pydantic_validator__.validate_python(data, self_instance=self)

ValidationError: 8 validation errors for Jobs
data.21.status.canceled_code
  Input should be 0, 1, 2, 3 or 4 [type=enum, input_value=6, input_type=int]
data.22.status.canceled_code
  Input should be 0, 1, 2, 3 or 4 [type=enum, input_value=6, input_type=int]
data.23.status.canceled_code
  Input should be 0, 1, 2, 3 or 4 [type=enum, input_value=6, input_type=int]
data.24.status.canceled_code
  Input should be 0, 1, 2, 3 or 4 [type=enum, input_value=6, input_type=int]
data.25.status.canceled_code
  Input should be 0, 1, 2, 3 or 4 [type=enum, input_value=6, input_type=int]
data.26.status.canceled_code
  Input should be 0, 1, 2, 3 or 4 [type=enum, input_value=6, input_type=int]
data.27.status.canceled_code
  Input should be 0, 1, 2, 3 or 4 [type=enum, input_value=6, input_type=int]
data.28.status.canceled_code
  Input should be 0, 1, 2, 3 or 4 [type=enum, input_value=6, input_type=int]
```

### Versions

Python 3.11.7
annotated-types==0.6.0
appnope @ file:///home/conda/feedstock_root/build_artifacts/appnope_1707233003401/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
attrs==23.2.0
backcall==0.2.0
beaker-gantry==0.21.0
beaker-py==1.26.3
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
click-help-colors==0.9.4
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1704278392174/work
contourpy==1.2.0
cycler==0.12.1
debugpy @ file:///private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_563_nwtkoc/croot/debugpy_1690905063850/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml==0.7.1
docker==6.1.3
docopt==0.6.2
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1704921103267/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1698579936712/work
fastjsonschema==2.19.1
filelock==3.13.1
fonttools==4.48.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.41
idna==3.6
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1703269254275/work
ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1707326353119/work
ipython==8.12.3
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
Jinja2==3.1.3
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter-console @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_62liw5pns2/croot/jupyter_console_1679999641189/work
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1699283905679/work
jupyter_core @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_782yoyc_98/croot/jupyter_core_1698937318631/work
jupyterlab_pygments==0.3.0
kiwisolver==1.4.5
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.2
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mdurl==0.1.2
mistune==3.0.2
mpmath==1.3.0
nbclient==0.9.0
nbconvert==7.16.1
nbformat==5.9.2
nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1705850609492/work
networkx==3.2.1
numpy==1.26.4
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1696202382185/work
pandas==2.2.0
pandocfilters==1.5.1
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
petname==2.6
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1706113125309/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
pillow==10.2.0
pipreqs==0.5.0
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1706713388748/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1702399386289/work
psutil @ file:///Users/cbousseau/work/recipes/ci_py311_2/psutil_1678995687212/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pydantic==2.6.1
pydantic_core==2.16.2
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1700607939962/work
pyparsing==3.1.1
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz==2024.1
PyYAML==6.0.1
pyzmq @ file:///private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_43pxpbos3z/croot/pyzmq_1705605108344/work
referencing==0.33.0
requests==2.31.0
rich==13.7.0
rpds-py==0.18.0
seaborn==0.13.2
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smmap==5.0.1
soupsieve==2.5
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
sympy==1.12
tinycss2==1.2.1
torch==2.2.0
torchaudio==2.2.0
torchvision==0.17.0
tornado @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_3a5nrn2jeh/croot/tornado_1696936974091/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1704212992681/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1702176139754/work
tzdata==2024.1
urllib3==2.2.0
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1704731205417/work
webencodings==0.5.1
websocket-client==1.7.0
yarg==0.1.9
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1695255097490/work

**Comment by epwalsh** [comment]
Hey @rbgirshick, thanks for all the detail. Fixed in https://github.com/allenai/beaker-py/commit/553dc587c21ecad47071a9856ddf196fc71ed27d, and I'll cut a new release.
